# fly.toml app configuration file generated for bisondrywall-io on 2023-11-15T16:21:01-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bisondrywall-io"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
