// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "./Icon.res.mjs";
import Link from "next/link";
import * as JsxRuntime from "react/jsx-runtime";

function Callout(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h2", {
                            children: "Get started with Bison Drywall",
                            className: "mb-4 bg-gradient-to-r from-yellow-dark via-black to-yellow-dark bg-clip-text py-1 text-3xl font-bold text-gray-50 text-transparent md:text-5xl"
                          }),
                      JsxRuntime.jsx("p", {
                            children: "Bison drywall is here to help with whatever you need. Reach out to us\n        today!",
                            className: "mx-auto max-w-xl text-white opacity-80"
                          }),
                      JsxRuntime.jsxs(Link, {
                            href: "mailto:bisondrywallllc@gmail.com",
                            className: "mt-8 inline-flex items-center rounded-xl bg-black px-8 py-4 font-medium text-white hover:scale-105 hover:transition-transform duration-200 ease-in-out",
                            children: [
                              "Contact us",
                              JsxRuntime.jsx(Icon.make, {
                                    name: "paper-plane-tilt",
                                    className: "fill-white ml-2"
                                  })
                            ]
                          })
                    ],
                    className: "callout p-12 text-center md:p-24"
                  }),
              className: "mx-auto max-w-screen-xl px-8 2xl:px-0"
            });
}

var make = Callout;

export {
  make ,
}
/* Icon Not a pure module */
