// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Icon(props) {
  var id = props.id;
  console.log(id);
  return JsxRuntime.jsx("svg", {
              children: JsxRuntime.jsx("use", {
                    href: "/sprite.svg#" + id
                  }),
              className: "w-6 h-6"
            });
}

var make = Icon;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
