// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

var offerings = [
  {
    id: 1,
    title: "Drywall installation",
    items: [
      {
        icon: "garage",
        label: "Residential",
        description: "Home extensions, wall additions, or simple patches, we work \
               quickly to accomodate any of your drywall needs."
      },
      {
        icon: "ph-buildings",
        label: "Commercial",
        description: "Looking for upgrades to the office? We help professional \
               businesses with additions and upgrade their suites."
      }
    ]
  },
  {
    id: 2,
    title: "Drywall & plaster repair",
    items: [
      {
        icon: "ph-disc",
        label: "Drywall cracks & holes",
        description: "Our team fixes damaged drywall caused by moisture, poor \
               installation, or even the settling of the structure."
      },
      {
        icon: "ph-fire",
        label: "Fire, smoke & water damage",
        description: "Recent fire or pipe burst? We remove the lingering smell of \
               smoke or mildew."
      }
    ]
  },
  {
    id: 3,
    title: "Drywall finishing",
    items: [
      {
        icon: "ph-paint-brush-household",
        label: "Plaster finishing",
        description: "Unfinished drywall doesn’t look the best. Let our professionals \
               help get your drywall ready for paint or paper."
      },
      {
        icon: "ph-wall",
        label: "Texture drywall",
        description: "Our team can help with any kind of texture you are looking \
               for—skip trowel, orange peel, sand, knockdown, and smooth!"
      }
    ]
  }
];

function OfferCards(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "What we offer",
                      className: "mb-8 text-center text-3xl font-bold text-gray-50 md:mb-16 md:text-5xl"
                    }),
                JsxRuntime.jsx("div", {
                      children: offerings.map(function (o) {
                            return JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsx("h3", {
                                                children: o.title,
                                                className: "text-center text-xl font-bold text-yellow-base md:text-3xl"
                                              }, String(o.id)),
                                          o.items.map(function (i) {
                                                return JsxRuntime.jsxs("div", {
                                                            children: [
                                                              JsxRuntime.jsx("span", {
                                                                    children: JsxRuntime.jsx("svg", {
                                                                          children: JsxRuntime.jsx("use", {
                                                                                href: "/sprite.svg#home"
                                                                              }),
                                                                          className: "w-6 h-6"
                                                                        })
                                                                  }),
                                                              JsxRuntime.jsxs("div", {
                                                                    children: [
                                                                      JsxRuntime.jsx("h4", {
                                                                            children: i.label,
                                                                            className: "mb-3 text-lg font-medium text-gray-50 md:text-xl"
                                                                          }),
                                                                      JsxRuntime.jsx("p", {
                                                                            children: i.description
                                                                          })
                                                                    ],
                                                                    className: "ml-4"
                                                                  })
                                                            ],
                                                            className: "mt-6 flex md:mt-12"
                                                          });
                                              })
                                        ],
                                        className: "rounded-[40px] bg-gray-700 p-8"
                                      });
                          }),
                      className: "grid grid-cols-1 gap-8 md:grid-cols-2 xl:grid-cols-3"
                    })
              ],
              className: "mx-auto max-w-screen-xl px-8 2xl:px-0"
            });
}

var make = OfferCards;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
