// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "./Icon.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function PhotosMarquee(props) {
  var photos = props.photos;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "Take a look at some before, during, and after photos of our work",
                      className: "mb-8 text-center text-3xl font-bold text-gray-50 md:mb-16 md:max-w-xl md:px-8 md:text-left md:text-5xl"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("div", {
                                    children: photos.slice(0, 49).map(function (photo) {
                                          return JsxRuntime.jsx("img", {
                                                      className: "h-[400px] w-[300px] max-w-[clamp(20rem,28vmin,20rem)] rounded-md object-cover shadow-md",
                                                      alt: photo.alt_text,
                                                      src: photo.source
                                                    }, photo.source);
                                        }),
                                    className: "animate-marquee flex min-w-full shrink-0 items-center justify-around gap-x-4"
                                  }),
                              className: "pointer-events-none relative flex gap-x-4 overflow-hidden"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("div", {
                                    children: photos.slice(49, 100).map(function (photo) {
                                          return JsxRuntime.jsx("img", {
                                                      className: "h-[400px] w-[300px] max-w-[clamp(20rem,28vmin,20rem)] rounded-md object-cover shadow-md",
                                                      alt: photo.alt_text,
                                                      src: photo.source
                                                    }, photo.source);
                                        }),
                                    className: "animate-marquee-reverse flex min-w-full shrink-0 items-center justify-around gap-x-4"
                                  }),
                              className: "pointer-events-none relative mt-4 flex gap-x-4 overflow-hidden"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsxs("a", {
                                    children: [
                                      "Check us out on Facebook",
                                      JsxRuntime.jsx(Icon.make, {
                                            name: "arrow-right",
                                            className: "fill-yellow-base ml-2",
                                            size: "18"
                                          })
                                    ],
                                    className: "hover-arrow float-right mt-4 inline-flex items-center text-gray-50",
                                    href: "https://m.facebook.com/bisondrywall"
                                  }),
                              className: "px-8"
                            })
                      ],
                      className: "relative flex flex-col justify-center overflow-hidden"
                    })
              ]
            });
}

var make = PhotosMarquee;

export {
  make ,
}
/* Icon Not a pure module */
