// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "./Icon.res.mjs";
import Link from "next/link";
import * as JsxRuntime from "react/jsx-runtime";

var testomonials = [
  {
    id: 1,
    initials: "AM",
    name: "Alex M.",
    review: "I would absolutely recommend using this Company. Great communication, \
         extremely fair priced, went above and beyond what was asked to make \
         sure the job was done correctly. Without a doubt, we will be reaching \
         back out to them in the future."
  },
  {
    id: 2,
    initials: "ZD",
    name: "Zach D.",
    review: "The guys were great, asked questions when they needed to and did high \
         quality work exactly to what I asked for. Anything that would have \
         been an issue was communicated with me effectively. Very satisfied \
         overall."
  },
  {
    id: 3,
    initials: "PM",
    name: "Pat M.",
    review: "Bison Drywall is a company that is professional,  has an excellent \
         talented team, and great prompt communication.  They were great to \
         work with and turned our drywall disasters  into a beautiful place.  \
         Thanks!"
  },
  {
    id: 4,
    initials: "BM",
    name: "Ben M.",
    review: "Ethan and his crew were great. Explained the process and continually \
         checked in if we had an questions or concerns. Great overall \
         experience and I highly recommend him and the whole Bison crew!"
  }
];

function Testomonials(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "Loved by the people of Wisconsin",
                      className: "mb-8 text-center text-3xl font-bold text-gray-50 md:mb-16 md:text-5xl"
                    }),
                JsxRuntime.jsx("div", {
                      children: testomonials.map(function (t) {
                            return JsxRuntime.jsx("div", {
                                        children: JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("div", {
                                                      children: JsxRuntime.jsx("span", {
                                                            children: JsxRuntime.jsx("span", {
                                                                  children: t.initials,
                                                                  className: "text-lg font-medium leading-none text-yellow-base opacity-75 md:text-xl"
                                                                }),
                                                            className: "inline-flex h-14 w-14 items-center justify-center rounded-full bg-gray-500"
                                                          }),
                                                      className: "flex-shrink-0"
                                                    }),
                                                JsxRuntime.jsxs("div", {
                                                      children: [
                                                        JsxRuntime.jsx("h3", {
                                                              children: t.name,
                                                              className: "mb-1 text-lg font-medium text-gray-50 md:text-xl"
                                                            }),
                                                        JsxRuntime.jsxs("div", {
                                                              children: [
                                                                JsxRuntime.jsx(Icon.make, {
                                                                      name: "star",
                                                                      className: "fill-yellow-base"
                                                                    }),
                                                                JsxRuntime.jsx(Icon.make, {
                                                                      name: "star",
                                                                      className: "fill-yellow-base"
                                                                    }),
                                                                JsxRuntime.jsx(Icon.make, {
                                                                      name: "star",
                                                                      className: "fill-yellow-base"
                                                                    }),
                                                                JsxRuntime.jsx(Icon.make, {
                                                                      name: "star",
                                                                      className: "fill-yellow-base"
                                                                    }),
                                                                JsxRuntime.jsx(Icon.make, {
                                                                      name: "star",
                                                                      className: "fill-yellow-base"
                                                                    })
                                                              ],
                                                              className: "flex items-center space-x-0.5"
                                                            }),
                                                        JsxRuntime.jsx("p", {
                                                              children: t.review,
                                                              className: "mt-4"
                                                            })
                                                      ],
                                                      className: "ml-3"
                                                    })
                                              ],
                                              className: "flex"
                                            }),
                                        className: "rounded-[40px] bg-gray-700 p-8"
                                      }, String(t.id));
                          }),
                      className: "grid grid-cols-1 gap-8 md:grid-cols-2"
                    }),
                JsxRuntime.jsxs(Link, {
                      href: "https://www.google.com/search?q=bisondrywall+appleton+wi&sourceid=chrome&ie=UTF-8#lrd=0x8803b936501f9d47:0x39d4b236558d2ad4,1,,,",
                      className: "hover-arrow float-right mt-4 inline-flex items-center text-gray-50",
                      children: [
                        "All reviews",
                        JsxRuntime.jsx(Icon.make, {
                              name: "arrow-right",
                              className: "fill-yellow-base ml-2",
                              size: "18"
                            })
                      ]
                    })
              ],
              className: "mx-auto max-w-screen-xl px-8 2xl:px-0"
            });
}

var make = Testomonials;

export {
  make ,
}
/* Icon Not a pure module */
