import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import Footer from '../src/components/Footer';
import OfferCards from '../src/components/OfferCards';
import PhotosMarquee from '../src/components/PhotosMarquee';
import Testomonials from '../src/components/Testomonials';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bison Drywall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="jumbotron">
        <div className="p-4">
          <Image
            src="/static/images/logo.png"
            alt="Bison Drywall logo"
            width={94}
            height={40}
          />
        </div>

        <div className="pt-24">
          <h1 className="text-center text-7xl font-bold text-white">
            Bison Drywall
          </h1>
          <h2 className="text-center text-2xl text-white opacity-50">
            Whatever your needs, Bison Drywall can help
          </h2>
        </div>
      </div>

      <main className="mt-8 w-full space-y-24 md:mt-16 md:space-y-48">
        <OfferCards />
        <PhotosMarquee />
        <Testomonials />
      </main>

      <Footer />

      <style jsx>{`
        .jumbotron {
          height: 550px;
          background: radial-gradient(
            circle at 50% -50%,
            #ddc253 0%,
            #161616 90%
          );
        }

        @media (min-width: 767px) {
          .jumbotron {
            background: radial-gradient(
              circle at 50% -50%,
              #ddc253 0%,
              #161616 80%
            );
          }
        }

        @media (min-width: 1280px) {
          .jumbotron {
            background: radial-gradient(
              circle at 50% -50%,
              #ddc253 0%,
              #161616 70%
            );
          }
        }

        @media (min-width: 1536px) {
          .jumbotron {
            background: radial-gradient(
              circle at 50% -50%,
              #ddc253 0%,
              #161616 55%
            );
          }
        }

        .marquee {
          position: relative;
          width: 100vw;
          max-width: 100%;
          overflow-x: hidden;
        }

        .track {
          position: absolute;
          white-space: nowrap;
        }

        .track > h1 {
          margin: 20px 0;
          font-size: 8rem;
          font-family: Antonio;
          -webkit-text-fill-color: rgba(255, 255, 255, 0);
          -webkit-text-stroke-width: 2px;
          -webkit-text-stroke-color: #f4955c;
          text-transform: uppercase;
        }
      `}</style>
    </>
  );
};

export default Home;
