// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./Home.res.mjs";
import * as Privacy from "./Privacy.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function App(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (match) {
    if (match.hd === "privacy" && !match.tl) {
      return JsxRuntime.jsx(Privacy.make, {});
    } else {
      return null;
    }
  } else {
    return JsxRuntime.jsx(Home.make, {});
  }
}

var make = App;

export {
  make ,
}
/* Home Not a pure module */
