// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OfferCards from "./components/OfferCards.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Home(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("img", {
                                    alt: "Bison Drywall logo",
                                    height: "40",
                                    src: "/logo.png",
                                    width: "94"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("h1", {
                                            children: "Bison Drywall",
                                            className: "text-4xl font-bold text-white sm:text-5xl md:text-7xl"
                                          }),
                                      JsxRuntime.jsx("h2", {
                                            children: "Whatever your needs, Bison Drywall can help",
                                            className: "mt-2 text-lg text-white opacity-50 md:text-2xl"
                                          }),
                                      JsxRuntime.jsx("a", {
                                            children: "Contact Us",
                                            className: "btn-grad mt-8 inline-flex items-center rounded-xl px-8 py-4 font-medium text-white md:mt-16",
                                            href: "mailto:bisondrywalllc.com"
                                          })
                                    ],
                                    className: "px-8 pt-24 text-center sm:px-0"
                                  })
                            ],
                            className: "p-4"
                          }),
                      className: "jumbotron"
                    }),
                JsxRuntime.jsx("main", {
                      children: JsxRuntime.jsx(OfferCards.make, {}),
                      className: "mt-8 w-full space-y-24 md:mt-16 md:space-y-48"
                    })
              ]
            });
}

var make = Home;

export {
  make ,
}
/* OfferCards Not a pure module */
