// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Callout from "./components/Callout.res.mjs";
import Head from "next/head";
import Link from "next/link";
import * as OfferCards from "./components/OfferCards.res.mjs";
import * as Testomonials from "./components/Testomonials.res.mjs";
import * as PhotosMarquee from "./components/PhotosMarquee.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var $$Response = {};

function $$default(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Head, {
                      children: JsxRuntime.jsx("title", {
                            children: "Bison Drywall"
                          })
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("img", {
                                    alt: "Bison Drywall logo",
                                    height: "40",
                                    src: "/logo.png",
                                    width: "94"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("h1", {
                                            children: "Bison Drywall",
                                            className: "text-4xl font-bold text-white sm:text-5xl md:text-7xl"
                                          }),
                                      JsxRuntime.jsx("h2", {
                                            children: "Whatever your needs, Bison Drywall can help",
                                            className: "mt-2 text-lg text-white opacity-50 md:text-2xl"
                                          }),
                                      JsxRuntime.jsx(Link, {
                                            href: "mailto:bisondrywalllc.com",
                                            className: "btn-grad mt-8 inline-flex items-center rounded-xl px-8 py-4 font-medium text-white md:mt-16",
                                            children: "Contact Us"
                                          })
                                    ],
                                    className: "px-8 pt-24 text-center sm:px-0"
                                  })
                            ],
                            className: "p-4"
                          }),
                      className: "jumbotron"
                    }),
                JsxRuntime.jsxs("main", {
                      children: [
                        JsxRuntime.jsx(OfferCards.make, {}),
                        JsxRuntime.jsx(PhotosMarquee.make, {
                              photos: props.photos
                            }),
                        JsxRuntime.jsx(Testomonials.make, {}),
                        JsxRuntime.jsx(Callout.make, {})
                      ],
                      className: "mt-8 w-full space-y-24 md:mt-16 md:space-y-48"
                    }),
                JsxRuntime.jsx("footer", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsx("img", {
                                          alt: "Bison Drywall logo",
                                          height: "20",
                                          src: "/logo.png",
                                          width: "47"
                                        })
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx(Link, {
                                            href: "mailto:bisondrywalllc.com",
                                            className: "mx-0 text-xs text-gray-300 hover:text-gray-200 xs:mx-2",
                                            children: "Contact Us"
                                          }),
                                      JsxRuntime.jsx(Link, {
                                            href: "/privacy",
                                            className: "mx-0 text-xs text-gray-300 hover:text-gray-200 xs:mx-2",
                                            children: "Privacy"
                                          }),
                                      JsxRuntime.jsx(Link, {
                                            href: "mailto:bisondrywalllc.com",
                                            className: "mx-0 text-xs text-gray-300 hover:text-gray-200 xs:mx-2",
                                            children: "Facebook"
                                          })
                                    ],
                                    className: "mt-4 flex flex-col space-x-0 space-y-4 xs:mt-0 xs:flex-row xs:space-y-0 xs:space-x-4"
                                  })
                            ],
                            className: "mx-auto flex max-w-7xl flex-col items-start justify-between py-4 xs:flex-row xs:items-center"
                          }),
                      className: "mt-24 md:mt-48 border-t border-gray-600 px-8 2xl:px-0"
                    })
              ]
            });
}

async function getServerSideProps(_ctx) {
  var token = process.env.FACEBOOK_API_TOKEN;
  var result;
  try {
    var response = await globalThis.fetch("https://graph.facebook.com/v14.0/112096071040835/photos?limit=100&fields=link,alt_text,source", {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer " + token
          }
        });
    var data = await response.json();
    var msg = data.error;
    if (msg == null) {
      var photos = data.data;
      result = (photos == null) ? ({
            TAG: "Error",
            _0: "No photos found"
          }) : ({
            TAG: "Ok",
            _0: photos
          });
    } else {
      result = {
        TAG: "Error",
        _0: msg
      };
    }
  }
  catch (exn){
    result = {
      TAG: "Error",
      _0: "Unexpected network error occurred"
    };
  }
  var props;
  props = result.TAG === "Ok" ? ({
        photos: result._0
      }) : ({
        photos: []
      });
  return Promise.resolve({
              props: props
            });
}

export {
  $$Response ,
  $$default as default,
  getServerSideProps ,
}
/* Callout Not a pure module */
