// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import * as JsxRuntime from "react/jsx-runtime";

function Privacy$TertiaryLink(props) {
  return JsxRuntime.jsx(Link, {
              href: props.href,
              className: "text-yellow-base underline hover:opacity-80",
              children: props.label
            });
}

function $$default() {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: "Privacy notice",
                              className: "text-3xl font-bold uppercase text-white md:text-5xl"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Last updated December 01, 2022"
                            })
                      ],
                      className: "pt-20"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                "Thank you for choosing to be part of our community at Bison Drywall\n            LLC. (&quot;Company&quot;, &quot;we&quot;, &quot;us&quot;,\n            &quot;our&quot;). We are committed to protecting your personal\n            information and your right to privacy. If you have any questions or\n            concerns about this privacy notice, or our practices with regards to\n            your personal information, please contact us at ",
                                JsxRuntime.jsx(Privacy$TertiaryLink, {
                                      href: "mailto:bisondrywallllc@gmail.com",
                                      label: "bisondrywallllc@gmail.com"
                                    }),
                                "."
                              ]
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                "When you visit our website ",
                                JsxRuntime.jsx(Privacy$TertiaryLink, {
                                      href: "https://bisondrywall.io",
                                      label: "https://bisondrywall.io"
                                    }),
                                " (the \"Website\"), and more generally, use any of our\n            services (the &quot;Services&quot;, which include the Website), we\n            appreciate that you are trusting us with your personal information.\n            We take your privacy very seriously. In this privacy notice, we seek\n            to explain to you in the clearest way possible what information we\n            collect, how we use it and what rights you have in relation to it.\n            We hope you take some time to read through it carefully, as it is\n            important. If there are any terms in this privacy notice that you do\n            not agree with, please discontinue use of our Services immediately."
                              ]
                            }),
                        JsxRuntime.jsx("div", {
                              children: "This privacy notice applies to all information collected through our\n            Services (which, as described above, includes our Website), as well\n            as, any related services, sales, marketing or events."
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Please read this privacy notice carefully as it will help you\n            understand what we do with the information that we collect.",
                              className: "font-bold text-gray-50"
                            })
                      ],
                      className: "space-y-4"
                    })
              ],
              className: "mx-auto max-w-4xl space-y-20 px-8 text-base lg:px-0"
            });
}

export {
  $$default as default,
}
/* next/link Not a pure module */
