// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Privacy(props) {
  return JsxRuntime.jsx("h1", {
              children: "Privacy"
            });
}

var make = Privacy;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
