// Generated by ReScript, PLEASE EDIT WITH CARE

import Head from "next/head";
import Link from "next/link";
import * as JsxRuntime from "react/jsx-runtime";

function Privacy$TertiaryLink(props) {
  return JsxRuntime.jsx(Link, {
              href: props.href,
              className: "text-yellow-base underline hover:opacity-80",
              children: props.label
            });
}

function $$default() {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Head, {
                      children: JsxRuntime.jsx("title", {
                            children: "Bison Drywall | Privacy"
                          })
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: "Privacy notice",
                              className: "text-3xl font-bold uppercase text-white md:text-5xl"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Last updated December 01, 2022"
                            })
                      ],
                      className: "pt-20"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                "Thank you for choosing to be part of our community at Bison Drywall\n            LLC. (\"Company\", \"we\", \"us\",\n            \"our\"). We are committed to protecting your personal\n            information and your right to privacy. If you have any questions or\n            concerns about this privacy notice, or our practices with regards to\n            your personal information, please contact us at ",
                                JsxRuntime.jsx(Privacy$TertiaryLink, {
                                      href: "mailto:bisondrywallllc@gmail.com",
                                      label: "bisondrywallllc@gmail.com"
                                    }),
                                "."
                              ]
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                "When you visit our website ",
                                JsxRuntime.jsx(Privacy$TertiaryLink, {
                                      href: "https://bisondrywall.io",
                                      label: "https://bisondrywall.io"
                                    }),
                                " (the \"Website\"), and more generally, use any of our\n            services (the \"Services\", which include the Website), we\n            appreciate that you are trusting us with your personal information.\n            We take your privacy very seriously. In this privacy notice, we seek\n            to explain to you in the clearest way possible what information we\n            collect, how we use it and what rights you have in relation to it.\n            We hope you take some time to read through it carefully, as it is\n            important. If there are any terms in this privacy notice that you do\n            not agree with, please discontinue use of our Services immediately."
                              ]
                            }),
                        JsxRuntime.jsx("div", {
                              children: "This privacy notice applies to all information collected through our\n            Services (which, as described above, includes our Website), as well\n            as, any related services, sales, marketing or events."
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Please read this privacy notice carefully as it will help you\n            understand what we do with the information that we collect.",
                              className: "font-bold text-gray-50"
                            })
                      ],
                      className: "space-y-4"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Table of contents",
                              className: "mb-8 text-xl font-bold uppercase text-white md:text-2xl"
                            }),
                        JsxRuntime.jsxs("ol", {
                              children: [
                                JsxRuntime.jsx("li", {
                                      children: JsxRuntime.jsx(Privacy$TertiaryLink, {
                                            href: "#1",
                                            label: "How do we use your information?"
                                          })
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: JsxRuntime.jsx(Privacy$TertiaryLink, {
                                            href: "#2",
                                            label: "Will your information be shared with anyone?"
                                          })
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: JsxRuntime.jsx(Privacy$TertiaryLink, {
                                            href: "#3",
                                            label: "Is your information transferred internationally?"
                                          })
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: JsxRuntime.jsx(Privacy$TertiaryLink, {
                                            href: "#4",
                                            label: "How long do we keep your information?"
                                          })
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: JsxRuntime.jsx(Privacy$TertiaryLink, {
                                            href: "#5",
                                            label: "How do we keep your information safe?"
                                          })
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: JsxRuntime.jsx(Privacy$TertiaryLink, {
                                            href: "#6",
                                            label: "What are your privacy rights?"
                                          })
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: JsxRuntime.jsx(Privacy$TertiaryLink, {
                                            href: "#7",
                                            label: "Controls for do-not-track features"
                                          })
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: JsxRuntime.jsx(Privacy$TertiaryLink, {
                                            href: "#8",
                                            label: "Do California residents have specific privacy rights?"
                                          })
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: JsxRuntime.jsx(Privacy$TertiaryLink, {
                                            href: "#9",
                                            label: "Do we make updates to this notice?"
                                          })
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: JsxRuntime.jsx(Privacy$TertiaryLink, {
                                            href: "#10",
                                            label: "How can you contact us about this notice?"
                                          })
                                    })
                              ],
                              className: "ml-8 list-outside list-decimal space-y-1"
                            })
                      ],
                      className: "space-y-4"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "How do we use your information?",
                              className: "mb-8 text-xl font-bold uppercase text-white md:text-2xl"
                            }),
                        JsxRuntime.jsxs("p", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: "In Short:",
                                      className: "font-medium"
                                    }),
                                "We process your\n            information for purposes based on legitimate business interests, the\n            fulfillment of our contract with you, compliance with our legal\n            obligations, and/or your consent."
                              ],
                              className: "italic"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "We use personal information collected via our Website for a variety\n            of business purposes described below. We process your personal\n            information for these purposes in reliance on our legitimate\n            business interests, in order to enter into or perform a contract\n            with you, with your consent, and/or for compliance with our legal\n            obligations. We indicate the specific processing grounds we rely on\n            next to each purpose listed below."
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("p", {
                                      children: "We use the information we collect or receive:"
                                    }),
                                JsxRuntime.jsxs("ul", {
                                      children: [
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "To send administrative information to you. ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We may use your personal information to send you product,\n                service and new feature information and/or information about\n                changes to our terms, conditions, and policies."
                                              ]
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "To protect our Services ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We may use your information as part of our efforts to keep our\n                Website safe and secure (for example, for fraud monitoring and\n                prevention)."
                                              ]
                                            }),
                                        JsxRuntime.jsx("li", {
                                              children: "To enforce our terms, conditions and policies for business\n                purposes, to comply with legal and regulatory requirements or in\n                connection with our contract.",
                                              className: "font-medium text-gray-50"
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "To respond to legal requests and prevent harm. ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "If we receive a subpoena or other legal request, we may need to\n                inspect the data we hold to determine how to respond."
                                              ]
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "Fulfill and manage your orders. ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We may use your information to fulfill and manage your orders,\n                payments, returns, and exchanges made through the Website."
                                              ]
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "Administer prize draws and competitions. ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We may use your information to administer prize draws and\n                competitions when you elect to participate in our competitions."
                                              ]
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "To deliver and facilitate delivery of services to the user. ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We may use your information to provide you with the requested\n                service."
                                              ]
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "To respond to user inquiries/offer support to users. ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We may use your information to respond to your inquiries and\n                solve any potential issues you might have with the use of our\n                Services."
                                              ]
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "To send you marketing and promotional communications. ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We and/or our third-party marketing partners may use the\n                personal information you send to us for our marketing purposes,\n                if this is in accordance with your marketing preferences. For\n                example, when expressing an interest in obtaining information\n                about us or our Website, subscribing to marketing or otherwise\n                contacting us, we will collect personal information from you.\n                You can opt-out of our marketing emails at any time (see the\n                \"WHAT ARE YOUR PRIVACY RIGHTS?\" below)."
                                              ]
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "Deliver targeted advertising to you. ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We may use your information to develop and display personalized\n                content and advertising (and work with third parties who do so)\n                tailored to your interests and/or location and to measure its\n                effectiveness."
                                              ]
                                            })
                                      ],
                                      className: "ml-8 list-outside list-disc space-y-1"
                                    })
                              ]
                            })
                      ],
                      className: "space-y-4",
                      id: "1"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Will your information be shared with anyone?",
                              className: "mb-8 text-xl font-bold uppercase text-white md:text-2xl"
                            }),
                        JsxRuntime.jsxs("p", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: "In Short:",
                                      className: "font-medium"
                                    }),
                                "We only share\n            information with your consent, to comply with laws, to provide you\n            with services, to protect your rights, or to fulfill business\n            obligations."
                              ],
                              className: "italic"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("p", {
                                      children: "We may process or share your data that we hold based on the\n              following legal basis:"
                                    }),
                                JsxRuntime.jsxs("ul", {
                                      children: [
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "Consent:",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We\n                may process your data if you have given us specific consent to\n                use your personal information for a specific purpose."
                                              ]
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "Legitimate Interests: ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We may process your data when it is reasonably necessary to\n                achieve our legitimate business interests."
                                              ]
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "Performance of a Contract: ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "Where we have entered into a contract with you, we may process\n                your personal information to fulfill the terms of our contract."
                                              ]
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "Legal Obligations: ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We may disclose your information where we believe it is\n                necessary to investigate, prevent, or take action regarding\n                potential violations of our policies, suspected fraud,\n                situations involving potential threats to the safety of any\n                person and illegal activities, or as evidence in litigation in\n                which we are involved. More specifically, we may need to process\n                your data or share your personal information in the following\n                situations:"
                                              ]
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "Vital Interests: ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We may disclose your information where we believe it is\n                necessary to investigate, prevent, or take action regarding\n                potential violations of our policies, suspected fraud,\n                situations involving potential threats to the safety of any\n                person and illegal activities, or as evidence in litigation in\n                which we are involved.",
                                                JsxRuntime.jsx("br", {}),
                                                "More specifically, we may need to process your data or share\n                your personal information in the following situations:"
                                              ]
                                            }),
                                        JsxRuntime.jsxs("li", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: "Business Transfers: ",
                                                      className: "font-medium text-gray-50"
                                                    }),
                                                "We may share or transfer your information in connection with, or\n                during negotiations of, any merger, sale of company assets,\n                financing, or acquisition of all or a portion of our business to\n                another company."
                                              ]
                                            })
                                      ],
                                      className: "ml-8 list-outside list-disc space-y-1"
                                    })
                              ]
                            })
                      ],
                      className: "space-y-4",
                      id: "2"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Is your information transferred internationally?",
                              className: "mb-8 text-xl font-bold uppercase text-white md:text-2xl"
                            }),
                        JsxRuntime.jsxs("p", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: "In Short:",
                                      className: "font-medium"
                                    }),
                                "We may transfer,\n            store, and process your information in countries other than your\n            own."
                              ],
                              className: "italic"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Our servers are located in the United States. If you are accessing\n            our Website from outside, please be aware that your information may\n            be transferred to, stored, and processed by us in our facilities and\n            by those third parties with whom we may share your personal\n            information (see \"WILL YOUR INFORMATION BE SHARED WITH\n            ANYONE?\" above), in and other countries."
                            }),
                        JsxRuntime.jsx("p", {
                              children: "If you are a resident in the European Economic Area (EEA) or United\n            Kingdom (UK), then these countries may not necessarily have data\n            protection laws or other similar laws as comprehensive as those in\n            your country. We will however take all necessary measures to protect\n            your personal information in accordance with this privacy notice and\n            applicable law."
                            })
                      ],
                      className: "space-y-4",
                      id: "3"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "How long do we keep your information?",
                              className: "mb-8 text-xl font-bold uppercase text-white md:text-2xl"
                            }),
                        JsxRuntime.jsxs("p", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: "In Short:",
                                      className: "font-medium"
                                    }),
                                "We keep your\n            information for as long as necessary to fulfill the purposes\n            outlined in this privacy notice unless otherwise required by law."
                              ],
                              className: "italic"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "We will only keep your personal information for as long as it is\n            necessary for the purposes set out in this privacy notice, unless a\n            longer retention period is required or permitted by law (such as\n            tax, accounting or other legal requirements). No purpose in this\n            notice will require us keeping your personal information for longer\n            than 90 days."
                            }),
                        JsxRuntime.jsx("p", {
                              children: "When we have no ongoing legitimate business need to process your\n            personal information, we will either delete or anonymize such\n            information, or, if this is not possible (for example, because your\n            personal information has been stored in backup archives), then we\n            will securely store your personal information and isolate it from\n            any further processing until deletion is possible."
                            })
                      ],
                      className: "space-y-4",
                      id: "4"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "How do we keep your information safe?",
                              className: "mb-8 text-xl font-bold uppercase text-white md:text-2xl"
                            }),
                        JsxRuntime.jsxs("p", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: "In Short:",
                                      className: "font-medium"
                                    }),
                                "We aim to protect your\n            personal information through a system of organizational and\n            technical security measures."
                              ],
                              className: "italic"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "We have implemented appropriate technical and organizational\n            security measures designed to protect the security of any personal\n            information we process. However, despite our safeguards and efforts\n            to secure your information, no electronic transmission over the\n            Internet or information storage technology can be guaranteed to be\n            100% secure, so we cannot promise or guarantee that hackers,\n            cybercriminals, or other unauthorized third parties will not be able\n            to defeat our security, and improperly collect, access, steal, or\n            modify your information. Although we will do our best to protect\n            your personal information, transmission of personal information to\n            and from our Website is at your own risk. You should only access the\n            Website within a secure environment."
                            })
                      ],
                      className: "space-y-4",
                      id: "5"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "What are your privacy rights?",
                              className: "mb-8 text-xl font-bold uppercase text-white md:text-2xl"
                            }),
                        JsxRuntime.jsxs("p", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: "In Short:",
                                      className: "font-medium"
                                    }),
                                "You may review,\n            change, or terminate your account at any time."
                              ],
                              className: "italic"
                            }),
                        JsxRuntime.jsxs("p", {
                              children: [
                                "If you are a resident in the EEA or UK and you believe we are\n            unlawfully processing your personal information, you also have the\n            right to complain to your local data protection supervisory\n            authority. You can find their contact details here: ",
                                JsxRuntime.jsx(Privacy$TertiaryLink, {
                                      href: "http://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm",
                                      label: "http://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm"
                                    }),
                                "."
                              ]
                            }),
                        JsxRuntime.jsxs("p", {
                              children: [
                                "If you are a resident in Switzerland, the contact details for the\n            data protection authorities are available here: ",
                                JsxRuntime.jsx(Privacy$TertiaryLink, {
                                      href: "https://www.edoeb.admin.ch/edoeb/en/home.html",
                                      label: "https://www.edoeb.admin.ch/edoeb/en/home.html"
                                    })
                              ]
                            })
                      ],
                      className: "space-y-4",
                      id: "6"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Controls for do-not-track features",
                              className: "mb-8 text-xl font-bold uppercase text-white md:text-2xl"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Most web browsers and some mobile operating systems and mobile\n            applications include a Do-Not-Track (\"DNT\") feature or\n            setting you can activate to signal your privacy preference not to\n            have data about your online browsing activities monitored and\n            collected. At this stage no uniform technology standard for\n            recognizing and implementing DNT signals has been finalized. As\n            such, we do not currently respond to DNT browser signals or any\n            other mechanism that automatically communicates your choice not to\n            be tracked online. If a standard for online tracking is adopted that\n            we must follow in the future, we will inform you about that practice\n            in a revised version of this privacy notice."
                            })
                      ],
                      className: "space-y-4",
                      id: "7"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Do California residents have specific privacy rights?",
                              className: "mb-8 text-xl font-bold uppercase text-white md:text-2xl"
                            }),
                        JsxRuntime.jsxs("p", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: "In Short:",
                                      className: "font-medium"
                                    }),
                                "Yes, if you are a\n            resident of California, you are granted specific rights regarding\n            access to your personal information."
                              ],
                              className: "italic"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "California Civil Code Section 1798.83, also known as the \"Shine\n            The Light\" law, permits our users who are California residents\n            to request and obtain from us, once a year and free of charge,\n            information about categories of personal information (if any) we\n            disclosed to third parties for direct marketing purposes and the\n            names and addresses of all third parties with which we shared\n            personal information in the immediately preceding calendar year. If\n            you are a California resident and would like to make such a request,\n            please submit your request in writing to us using the contact\n            information provided below."
                            }),
                        JsxRuntime.jsx("p", {
                              children: "If you are under 18 years of age, reside in California, and have a\n            registered account with the Website, you have the right to request\n            removal of unwanted data that you publicly post on the Website. To\n            request removal of such data, please contact us using the contact\n            information provided below, and include the email address associated\n            with your account and a statement that you reside in California. We\n            will make sure the data is not publicly displayed on the Website,\n            but please be aware that the data may not be completely or\n            comprehensively removed from all our systems (e.g. backups, etc.)."
                            })
                      ],
                      className: "space-y-4",
                      id: "8"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Do we make changes to this notice?",
                              className: "mb-8 text-xl font-bold uppercase text-white md:text-2xl"
                            }),
                        JsxRuntime.jsxs("p", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: "In Short:",
                                      className: "font-medium"
                                    }),
                                "Yes, we will update\n            this notice as necessary to stay compliant with relevant laws."
                              ],
                              className: "italic"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "We may update this privacy notice from time to time. The updated\n            version will be indicated by an updated \"Revised\" date and\n            the updated version will be effective as soon as it is accessible.\n            If we make material changes to this privacy notice, we may notify\n            you either by prominently posting a notice of such changes or by\n            directly sending you a notification. We encourage you to review this\n            privacy notice frequently to be informed of how we are protecting\n            your information."
                            })
                      ],
                      className: "space-y-4",
                      id: "9"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "How can you contact us about this notice?",
                              className: "mb-8 text-xl font-bold uppercase text-white md:text-2xl"
                            }),
                        JsxRuntime.jsxs("p", {
                              children: [
                                "If you have questions or comments about this notice, you may email\n            us at ",
                                JsxRuntime.jsx(Privacy$TertiaryLink, {
                                      href: "mailto:bisondrywallllc@gmail.com",
                                      label: "bisondrywallllc@gmail.com"
                                    }),
                                " or by post to:"
                              ]
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("p", {
                                      children: "Bison Drywall LLC."
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "Menasha, WI 54952"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "United States"
                                    })
                              ]
                            })
                      ],
                      className: "space-y-4 pb-20",
                      id: "10"
                    })
              ],
              className: "mx-auto max-w-4xl space-y-20 px-8 text-base lg:px-0"
            });
}

export {
  $$default as default,
}
/* next/head Not a pure module */
