// Generated by ReScript, PLEASE EDIT WITH CARE

import Head from "next/head";
import * as JsxRuntime from "react/jsx-runtime";

function MainLayout(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsxs(Head, {
                      children: [
                        JsxRuntime.jsx("link", {
                              href: "https://fonts.googleapis.com",
                              rel: "preconnect"
                            }),
                        JsxRuntime.jsx("link", {
                              href: "https://fonts.gstatic.com",
                              rel: "preconnect"
                            }),
                        JsxRuntime.jsx("link", {
                              href: "https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap",
                              rel: "stylesheet"
                            })
                      ]
                    }),
                props.children
              ]
            });
}

var make = MainLayout;

export {
  make ,
}
/* next/head Not a pure module */
